---

AllCops:
  TargetRubyVersion: 2.3

Metrics/ClassLength:
  Max: 400

Style/HashEachMethods:
    Enabled: true
Style/HashTransformKeys:
    Enabled: true
Style/HashTransformValues:
    Enabled: true
