---
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

Layout/LineLength:
  Max: 80 # Is nothing sacred?
Metrics/ClassLength:
  Max: 400
Naming/VariableNumber:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false # because it wants to make lines >80 chars
Style/OptionalBooleanParameter:
  Enabled: false
