---

AllCops:
  TargetRubyVersion: 2.4

Metrics/ClassLength:
  Max: 400

Style/IfUnlessModifier:
  Enabled: false # because it wants to make lines >80 chars

Style/HashEachMethods:
    Enabled: true
Style/HashTransformKeys:
    Enabled: true
Style/HashTransformValues:
    Enabled: true
