AllCops:
  TargetRubyVersion: 2.2

Style/FormatStringToken:
  Enabled: false

# Allow long blocks of tests
#
Metrics/BlockLength:
  Max: 120

Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ModuleLength:
  Max: 200
