---
Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 45

Metrics/ClassLength:
  Max: 300

Style/HashEachMethods:
    Enabled: true
Style/HashTransformKeys:
    Enabled: true
Style/HashTransformValues:
    Enabled: true
